-- PrintPetz — insert the 47 expansion themes
-- Generated 2026-09-13. NOT run by Claude. Review, then apply in Supabase.
--
-- Prerequisites, in order:
--   1. migrate-styles-category-variants.sql  (adds the variants column)
--   2. the code on branch feat/theme-expansion deployed
--      (every theme below names a surface that only exists once
--       NAME_PLACEMENTS knows about it)
--
-- NO ids are supplied: the rows rely on the styles.id default. If id has no
-- default this will fail loudly rather than collide with an existing row.
--
-- image is set to the empty string. These themes will render correctly but
-- will have no thumbnail in the picker until real URLs are filled in. The
-- final query in this file lists exactly which rows still need one.

begin;

-- Guard: expect 0. A non-zero count means some of these names already exist
-- and this file would create duplicates.
select count(*) as should_be_zero
from public.styles
where name in ('Rowing', 'Archery', 'Curling', 'Darts', 'Billiards', 'Bowling', 'Sailboat Racer', 'Race Car Driver', 'Motocross Racer', 'Softball', 'Swimmer', 'Rugby', 'Lacrosse', 'Field Hockey', 'Track and Field', 'Tennis', 'Aussie Rules Football', 'Santa Claus', 'Mrs. Claus', 'Elf', 'Gingerbread Man', 'Snowman', 'Christmas Angel', 'Christmas Fairy', 'Wise Man', 'Nativity Visitor', 'Cosy Christmas', 'Reindeer Helper', 'Pilgrim', 'Harvest Chef', 'Autumn Portrait', 'Uncle Sam', 'Stars and Stripes', 'Backyard Barbecue', 'Founding Father', 'Roman Emperor', 'Egyptian Pharaoh', 'Napoleonic General', 'Medieval Queen', 'Viking Chieftain', 'Samurai', 'Jazz Age Dapper', 'Caped Hero', 'Armoured Tech Hero', 'Masked Vigilante', 'Flying Hero', 'Super Strength Hero');

insert into public.styles (name, category, image, base_prompt, variants) values
-- Rowing (Sports) — 62 words | worst assembled: Natural 314 / Mascot 318 / Cartoon 320
  ('Rowing', 'Sports', '', 'Cute [TRIGGER_WORD] as a rower, upright by the water. Wearing a plain sleeveless rowing singlet, plain fitted shorts to mid-thigh, and plain low deck shoes. Fur shows on the head, forepaws, lower legs and tail. Both forepaws grip exactly one long wooden oar by the handle. A racing shell rests at the bank behind. Calm river background, dramatic lighting, ultra detailed 8K.', '["lifting the oar clear of the water, side profile camera, mist behind","shouldering the oar at the boathouse, three-quarter camera, river glinting","close portrait from the chest up, dawn light, water soft behind","wide full-body framing on the landing stage, racing shell beyond","turning toward the camera mid-stride, low angle, rowing club behind"]'::jsonb),
-- Archery (Sports) — 70 words | worst assembled: Natural 329 / Mascot 333 / Cartoon 335
  ('Archery', 'Sports', '', 'Cute [TRIGGER_WORD] as an archer, upright at the shooting line. Wearing a plain leather arm guard, a plain quilted jerkin, plain canvas trousers covering both legs to the ankle, and soft leather boots. A plain leather quiver strap crosses the chest. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one recurve bow with one arrow nocked. Open archery field background, dramatic lighting, ultra detailed 8K.', '["drawing the bow to full extension, side profile camera, targets distant behind","bow lowered at rest, wide full-body framing, field stretching away","close portrait from the chest up, sunlit, blurred targets behind","sighting down the arrow, low three-quarter camera, long grass around","turning from the line, three-quarter camera, quivers racked behind"]'::jsonb),
-- Curling (Sports) — 64 words | worst assembled: Natural 318 / Mascot 322 / Cartoon 324
  ('Curling', 'Sports', '', 'Cute [TRIGGER_WORD] as a curler, upright on the ice sheet. Wearing a plain zipped curling jacket, plain stretch trousers covering both legs to the ankle, and plain gripper shoes. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one curling broom by the handle. A granite stone waits on the ice ahead. Curling rink background, dramatic lighting, ultra detailed 8K.', '["sweeping ahead of the stone, low three-quarter camera, house markings behind","broom raised in celebration, wide full-body framing, rink lights above","close portrait from the chest up, cool light, sheet receding behind","watching the stone travel, side profile camera, scoreboard blurred beyond","turning to the camera mid-stride, ice gleaming, figures out of focus"]'::jsonb),
-- Darts (Sports) — 63 words | worst assembled: Natural 313 / Mascot 317 / Cartoon 320
  ('Darts', 'Sports', '', 'Cute [TRIGGER_WORD] as a darts player, upright at the oche. Wearing a plain collared darts shirt, plain dark trousers covering both legs to the ankle, and plain flat shoes. Fur shows only on the head, forepaws and tail. One forepaw holds exactly one dart ready to throw. A plain dartboard hangs on the wall ahead. Dim venue background, dramatic lighting, ultra detailed 8K.', '["mid-throw with the arm extended, side profile camera, board sharp ahead","close portrait from the chest up, spotlight warm, venue dark behind","wide full-body framing at the oche, board and lighting rig beyond","arm raised in celebration, low three-quarter camera, venue lights flaring","lining up the throw, front-on camera, board glowing ahead"]'::jsonb),
-- Billiards (Sports) — 68 words | worst assembled: Natural 324 / Mascot 328 / Cartoon 330
  ('Billiards', 'Sports', '', 'Cute [TRIGGER_WORD] as a billiards player, upright at the table. Wearing a plain white collared shirt, a plain dark waistcoat, plain dark trousers covering both legs to the ankle, and polished shoes. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one wooden cue by the shaft. Green baize and scattered balls fill the table ahead. Club room background, dramatic lighting, ultra detailed 8K.', '["lining up the shot along the cue, low table-level camera, pockets beyond","chalking the cue tip, three-quarter camera, lamp glow overhead","close portrait from the chest up, warm lamplight, baize soft behind","wide full-body framing beside the table, club room receding","straightening after the shot, side profile camera, balls scattered ahead"]'::jsonb),
-- Bowling (Sports) — 63 words | worst assembled: Natural 321 / Mascot 325 / Cartoon 328
  ('Bowling', 'Sports', '', 'Cute [TRIGGER_WORD] as a bowler, upright on the approach. Wearing a plain two-tone bowling shirt, plain dark trousers covering both legs to the ankle, and plain bowling shoes. Fur shows only on the head, forepaws and tail. Both forepaws cradle exactly one bowling ball at chest height. Polished lanes stretch ahead under bright house lights. Bowling alley background, dramatic lighting, ultra detailed 8K.', '["mid-approach toward the foul line, side profile camera, pins bright ahead","ball raised at the ready, front-on camera, lanes converging behind","close portrait from the chest up, neon glow, lanes soft behind","wide full-body framing on the approach, ball return beside","arm raised in celebration, low three-quarter camera, pins scattered ahead"]'::jsonb),
-- Sailboat Racer (Sports) — 69 words | worst assembled: Natural 327 / Mascot 331 / Cartoon 333
  ('Sailboat Racer', 'Sports', '', 'Cute [TRIGGER_WORD] as a sailboat racer, upright on the foredeck. Wearing a plain waterproof sailing jacket, a plain buoyancy vest over it, plain quick-dry trousers covering both legs to the ankle, and grippy deck boots. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one taut rope line. A racing dinghy carries them with sails filling behind. Open water background, dramatic lighting, ultra detailed 8K.', '["hauling the line taut, low three-quarter camera, spray bursting behind","close portrait from the chest up, sea light, sails blurred behind","wide full-body framing on the foredeck, horizon tilting beyond","facing into the wind, side profile camera, wake streaming behind","turning toward the camera, mast rising above, open water around"]'::jsonb),
-- Race Car Driver (Sports) — 75 words | worst assembled: Natural 329 / Mascot 333 / Cartoon 336
  ('Race Car Driver', 'Sports', '', 'Cute [TRIGGER_WORD] as a race car driver, upright in the pit lane. Wearing a plain fireproof racing suit zipped to the collar, a plain chest panel at the centre, plain racing gloves over both forepaws, and plain racing boots. Fur shows only on the head and tail. The helmet is off, held under one forepaw, face fully visible. A race car waits behind with plain unmarked bodywork. Pit lane background, dramatic lighting, ultra detailed 8K.', '["raising a fist in celebration, low heroic camera, pit crew blurred behind","walking the pit lane, side profile camera, garages receding behind","close portrait from the chest up, harsh daylight, car soft behind","wide full-body framing beside the car, pit boards and tyres beyond","turning toward the camera, three-quarter framing, pit lights overhead"]'::jsonb),
-- Motocross Racer (Sports) — 66 words | worst assembled: Natural 320 / Mascot 324 / Cartoon 326
  ('Motocross Racer', 'Sports', '', 'Cute [TRIGGER_WORD] as a motocross racer, upright at the track edge. Wearing a plain long-sleeved motocross jersey, a plain chest protector over it, plain padded trousers covering both legs to the ankle, and tall riding boots. Fur shows only on the head, forepaws and tail. The helmet is off, resting on the seat beside them, face fully visible. Dirt track background, dramatic lighting, ultra detailed 8K.', '["dust settling around, three-quarter camera, berms rising behind","wide full-body framing beside the bike, track churned beyond","close portrait from the chest up, sunlit dust, track soft behind","arm raised in celebration, low heroic camera, spectators far behind","walking the track line, side profile camera, jumps stretching away"]'::jsonb),
-- Softball (Sports) — 74 words | worst assembled: Natural 333 / Mascot 337 / Cartoon 339
  ('Softball', 'Sports', '', 'Cute [TRIGGER_WORD] as a softball player, upright at the plate. Wearing a plain softball jersey, plain fabric trousers covering both legs to the ankle, a belt at the waist, and a plain solid-colour cap with a blank front panel. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one metal softball bat by the handle. One yellow-green softball waits on the ground behind. Ballpark background, dramatic lighting, ultra detailed 8K.', '["mid-swing through the zone, low three-quarter camera, floodlights glaring","bat raised at the ready, front-on camera, backstop netting behind","close portrait from the chest up, dusk light, outfield soft behind","wide full-body framing at the plate, dugout beyond","walking toward the camera, three-quarter framing, infield dirt underfoot"]'::jsonb),
-- Swimmer (Sports) — 67 words | worst assembled: Natural 322 / Mascot 326 / Cartoon 328
  ('Swimmer', 'Sports', '', 'Cute [TRIGGER_WORD] as a swimmer, upright at the pool edge. Wearing a plain racing swimsuit, a plain silicone swim cap, a plain towel draped over one shoulder, and plain poolside sandals. The goggles are pushed up on the forehead, face fully visible. Fur shows on the head, forepaws, lower legs and tail. Lane ropes stretch across the water behind. Indoor pool background, dramatic lighting, ultra detailed 8K.', '["shaking water clear, three-quarter camera, lane ropes bright behind","close portrait from the chest up, pool light rippling behind","wide full-body framing at the blocks, lanes receding beyond","arm raised in celebration, low heroic camera, scoreboard glowing behind","turning toward the camera, water beading, pool hall soft behind"]'::jsonb),
-- Rugby (Sports) — 65 words | worst assembled: Natural 317 / Mascot 321 / Cartoon 324
  ('Rugby', 'Sports', '', 'Cute [TRIGGER_WORD] as a rugby player, upright on the pitch. Wearing a plain hooped rugby jersey, plain fabric shorts, tall plain socks covering both lower legs, and studded boots. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one rugby ball against the chest. Goal posts rise at the far end of the field. Stadium background, dramatic lighting, ultra detailed 8K.', '["mid-stride with the ball tucked, low three-quarter camera, posts beyond","ball raised in celebration, wide full-body framing, crowd far behind","close portrait from the chest up, floodlit, pitch soft behind","turning upfield, side profile camera, churned turf underfoot","facing the camera at the halfway line, posts rising behind"]'::jsonb),
-- Lacrosse (Sports) — 68 words | worst assembled: Natural 325 / Mascot 329 / Cartoon 332
  ('Lacrosse', 'Sports', '', 'Cute [TRIGGER_WORD] as a lacrosse player, upright on the field. Wearing a plain mesh lacrosse jersey, plain padded shorts, tall plain socks covering both lower legs, and cleated boots. Fur shows only on the head, forepaws and tail. The helmet is off, resting on the grass beside them, face fully visible. Both forepaws grip exactly one lacrosse stick by the shaft. Field background, dramatic lighting, ultra detailed 8K.', '["cradling the stick mid-stride, low three-quarter camera, goal beyond","stick raised in celebration, wide full-body framing, field stretching away","close portrait from the chest up, afternoon light, field soft behind","turning upfield, side profile camera, long shadows across the grass","facing the camera at midfield, goal posts small behind"]'::jsonb),
-- Field Hockey (Sports) — 65 words | worst assembled: Natural 347 / Mascot 351 / Cartoon 353
  ('Field Hockey', 'Sports', '', 'Cute [TRIGGER_WORD] as a field hockey player, upright on the turf. Wearing a plain short-sleeved field hockey jersey, plain fabric shorts, tall plain socks covering both lower legs, and turf shoes. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one field hockey stick by the handle. One ball waits on the turf ahead. Pitch background, dramatic lighting, ultra detailed 8K.', '["driving the ball forward, low three-quarter camera, pitch lines receding","stick raised in celebration, wide full-body framing, goal beyond","close portrait from the chest up, bright turf glowing behind","turning upfield, side profile camera, blue turf stretching away","facing the camera at the circle, goal small behind"]'::jsonb),
-- Track and Field (Sports) — 58 words | worst assembled: Natural 316 / Mascot 320 / Cartoon 323
  ('Track and Field', 'Sports', '', 'Cute [TRIGGER_WORD] as a track athlete, upright on the track. Wearing a plain sleeveless running singlet, plain fitted shorts to mid-thigh, plain wrist tape on both forearms, and plain spiked running shoes. Fur shows on the head, forepaws, lower legs and tail. Painted lanes curve away behind under stadium floodlights. Athletics stadium background, dramatic lighting, ultra detailed 8K.', '["mid-stride down the lane, side profile camera, track blurring past","arms raised in celebration, low heroic camera, floodlights flaring above","close portrait from the chest up, sunlit, stadium soft behind","wide full-body framing on the start line, lanes receding beyond","turning toward the camera, three-quarter framing, infield green behind"]'::jsonb),
-- Tennis (Sports) — 66 words | worst assembled: Natural 321 / Mascot 325 / Cartoon 327
  ('Tennis', 'Sports', '', 'Cute [TRIGGER_WORD] as a tennis player, upright at the baseline. Wearing a plain collared tennis shirt, plain fitted shorts to mid-thigh, a plain wristband on one forearm, and plain court shoes. Fur shows on the head, forepaws, lower legs and tail. Both forepaws grip exactly one tennis racket by the handle. One ball waits on the court behind. Tennis court background, dramatic lighting, ultra detailed 8K.', '["mid-serve with the racket high, low three-quarter camera, net beyond","racket raised in celebration, wide full-body framing, crowd far behind","close portrait from the chest up, bright daylight, court soft behind","waiting to receive at the baseline, front-on camera, net ahead","turning toward the camera, three-quarter framing, court lines receding"]'::jsonb),
-- Aussie Rules Football (Sports) — 64 words | worst assembled: Natural 346 / Mascot 350 / Cartoon 352
  ('Aussie Rules Football', 'Sports', '', 'Cute [TRIGGER_WORD] as an Aussie rules footballer, upright on the oval. Wearing a plain sleeveless jersey, plain fitted shorts to mid-thigh, tall plain socks covering both lower legs, and studded boots. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one oval football against the chest. Goal posts rise at the far end. Oval background, dramatic lighting, ultra detailed 8K.', '["mid-stride with the football tucked, low three-quarter camera, posts beyond","football raised in celebration, wide full-body framing, oval stretching away","close portrait from the chest up, bright sun, oval soft behind","turning upfield, side profile camera, long shadows across the grass","facing the camera at the centre circle, posts rising behind"]'::jsonb),
-- Santa Claus (Christmas) — 78 words | worst assembled: Natural 333 / Mascot 337 / Cartoon 340
  ('Santa Claus', 'Christmas', '', 'Cute [TRIGGER_WORD] as Santa, upright on Christmas Eve. Wearing a plain red velvet coat with white plush trim, plain red trousers covering both legs to the ankle, tall black boots, and a plain red hat set back from the eyes. A wide black belt with a plain square buckle sits at the waist. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one bulging gift sack. Snowy fireside background, warm lighting, ultra detailed 8K.', '["hoisting the gift sack over one shoulder, low three-quarter camera, snow falling","mid-stride toward the hearth, side profile camera, stockings hung behind","close portrait from the chest up, firelight warm, tree lights bokeh behind","wide full-body framing beside the decorated tree, garlands glowing behind","turning back with a wave, three-quarter camera, snowy rooftops behind"]'::jsonb),
-- Mrs. Claus (Christmas) — 68 words | worst assembled: Natural 317 / Mascot 321 / Cartoon 324
  ('Mrs. Claus', 'Christmas', '', 'Cute [TRIGGER_WORD] as Mrs. Claus, upright in a warm kitchen. Wearing a plain red wool dress to the ankle, a plain white apron over it, a plain lace collar, and soft house shoes. Round spectacles sit low on the face, fully visible. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one tray of iced biscuits. Cosy kitchen background, warm lighting, ultra detailed 8K.', '["sliding a tray from the oven, three-quarter camera, kitchen warm behind","close portrait from the chest up, soft lamplight, shelves soft behind","wide full-body framing by the counter, garlands strung above","offering the tray toward the camera, front-on framing, steam rising","turning from the stove, side profile camera, window frosted behind"]'::jsonb),
-- Elf (Christmas) — 67 words | worst assembled: Natural 320 / Mascot 324 / Cartoon 326
  ('Elf', 'Christmas', '', 'Cute [TRIGGER_WORD] as a Christmas elf, upright in the workshop. Wearing a plain green felt tunic with a wide plain belt, plain striped stockings covering both legs to the ankle, curled leather shoes, and a plain pointed green hat with a small bell. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one wooden toy. Toy workshop background, warm lighting, ultra detailed 8K.', '["holding the toy up to inspect, three-quarter camera, workbench behind","close portrait from the chest up, lamplight warm, shelves soft behind","wide full-body framing beside the bench, tools and shavings around","mid-stride across the workshop, side profile camera, garlands strung above","turning toward the camera with a grin, low angle, workshop glowing"]'::jsonb),
-- Gingerbread Man (Christmas) — 67 words | worst assembled: Natural 320 / Mascot 324 / Cartoon 327
  ('Gingerbread Man', 'Christmas', '', 'Cute [TRIGGER_WORD] as a gingerbread character, upright on a baking table. Wearing a plain brown quilted onesie piped with white icing at the cuffs and hem, round gumdrop buttons down the chest, a plain icing panel across the chest, and soft brown boots. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one candy cane. Warm bakery background, warm lighting, ultra detailed 8K.', '["holding the candy cane aloft, three-quarter camera, flour dusting the air","close portrait from the chest up, oven glow warm behind","wide full-body framing on the table, cutters scattered around","mid-stride across the table, side profile camera, baking tins behind","turning toward the camera, low angle, icing bowls soft behind"]'::jsonb),
-- Snowman (Christmas) — 71 words | worst assembled: Natural 321 / Mascot 325 / Cartoon 328
  ('Snowman', 'Christmas', '', 'Cute [TRIGGER_WORD] as a snowman character, upright in deep snow. Wearing a plain white padded suit covering the torso and both legs to the boot, a plain knit scarf around the neck, plain mittens over both forepaws, and a plain black top hat set back from the eyes. Fur shows only on the head and tail. Both forepaws hold exactly one twig broom. Snowy field background, dramatic lighting, ultra detailed 8K.', '["holding the broom high, wide full-body framing, snow drifting past","close portrait from the chest up, cold blue light, snow falling","mid-stride through the drifts, side profile camera, pine trees behind","turning toward the camera, low angle, moonlit snow stretching away","broom raised in greeting, three-quarter camera, distant cottage glowing"]'::jsonb),
-- Christmas Angel (Christmas) — 68 words | worst assembled: Natural 321 / Mascot 325 / Cartoon 327
  ('Christmas Angel', 'Christmas', '', 'Cute [TRIGGER_WORD] as a Christmas angel, upright in soft light. Wearing a plain white linen robe to the floor, a plain gold sash across the chest, and plain sandals. Broad feathered wings rise from the shoulders and a plain gold halo floats above the head. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one slim candle. Starlit background, dramatic lighting, ultra detailed 8K.', '["lifting the candle higher, three-quarter camera, stars scattered behind","close portrait from the chest up, golden light, wings soft behind","wide full-body framing with wings spread, clouds glowing beyond","turning toward the camera, low heroic angle, halo bright above","mid-stride through soft light, side profile camera, stars drifting"]'::jsonb),
-- Christmas Fairy (Christmas) — 59 words | worst assembled: Natural 313 / Mascot 317 / Cartoon 319
  ('Christmas Fairy', 'Christmas', '', 'Cute [TRIGGER_WORD] as a Christmas fairy, upright among branches. Wearing a plain silver tulle dress to the knee, a plain ribbon sash across the chest, and soft slippers. Translucent wings rise from the shoulders. Fur shows on the head, forepaws, lower legs and tail. Both forepaws grip exactly one star-tipped wand. Glittering tree background, warm lighting, ultra detailed 8K.', '["raising the wand, three-quarter camera, tree lights bokeh behind","close portrait from the chest up, sparkle soft, branches behind","wide full-body framing with wings spread, ornaments glowing beyond","turning toward the camera, low angle, tree lights scattered behind","mid-stride along a branch, side profile camera, tinsel shimmering"]'::jsonb),
-- Wise Man (Christmas) — 69 words | worst assembled: Natural 318 / Mascot 322 / Cartoon 325
  ('Wise Man', 'Christmas', '', 'Cute [TRIGGER_WORD] as a wise man traveller, upright on a desert road. Wearing a rich plain crimson robe to the ankle, a plain gold sash across the chest, a plain wrapped turban, and leather sandals. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one small gift box. A bright star hangs low in the night sky. Desert night background, dramatic lighting, ultra detailed 8K.', '["holding the gift box forward, three-quarter camera, star bright above","close portrait from the chest up, warm light, dunes soft behind","wide full-body framing on the road, caravan silhouettes far behind","turning toward the camera, low angle, night sky vast behind","mid-stride across the sand, side profile camera, star trailing above"]'::jsonb),
-- Nativity Visitor (Christmas) — 66 words | worst assembled: Natural 319 / Mascot 323 / Cartoon 325
  ('Nativity Visitor', 'Christmas', '', 'Cute [TRIGGER_WORD] as a shepherd visiting the stable, upright outside its doorway. Wearing a plain undyed wool robe to the ankle, a plain cloth sash across the chest, a plain head cloth, and leather sandals. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one wooden crook. A lamb waits quietly beside them. Stable at night background, dramatic lighting, ultra detailed 8K.', '["raising the crook, three-quarter camera, star bright above the stable","close portrait from the chest up, warm light, straw soft behind","wide full-body framing outside the stable, lamb close beside","turning toward the camera, low angle, night sky vast behind","mid-stride toward the doorway, side profile camera, warm glow ahead"]'::jsonb),
-- Cosy Christmas (Christmas) — 63 words | worst assembled: Natural 315 / Mascot 319 / Cartoon 321
  ('Cosy Christmas', 'Christmas', '', 'Cute [TRIGGER_WORD] in a cosy Christmas scene, upright by the fire. Wearing a plain cable-knit sweater, plain soft trousers covering both legs to the ankle, thick knit socks, and a plain knit hat set back from the eyes. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one steaming mug of cocoa. Fireside background, warm lighting, ultra detailed 8K.', '["lifting the mug toward the camera, three-quarter framing, fire glowing behind","close portrait from the chest up, firelight warm, garlands soft behind","wide full-body framing beside the hearth, stockings hung above","turning toward the camera, low angle, tree lights bokeh behind","mid-stride across the rug, side profile camera, window snow beyond"]'::jsonb),
-- Reindeer Helper (Christmas) — 75 words | worst assembled: Natural 326 / Mascot 330 / Cartoon 332
  ('Reindeer Helper', 'Christmas', '', 'Cute [TRIGGER_WORD] as a reindeer helper, upright in the snow. Wearing a plain brown plush onesie with a soft antler hood pushed down onto the back, a plain leather collar with a plain tag and sleigh bells, and soft boots. The face is fully visible with a red nose. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one strand of harness bells. Snowy paddock background, warm lighting, ultra detailed 8K.', '["shaking the bells, three-quarter camera, snow drifting past","close portrait from the chest up, warm light, snowfall soft behind","wide full-body framing in the paddock, fence line stretching behind","turning toward the camera, low angle, snowy hills beyond","mid-stride through the snow, side profile camera, lights strung above"]'::jsonb),
-- Pilgrim (Thanksgiving) — 73 words | worst assembled: Natural 327 / Mascot 331 / Cartoon 333
  ('Pilgrim', 'Thanksgiving', '', 'Cute [TRIGGER_WORD] as a pilgrim, upright on a harvest lane. Wearing a plain black wool coat with a wide white collar, a plain cloth sash across the chest, plain black trousers covering both legs to the ankle, and buckled shoes. A tall buckled hat sits back from the eyes. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one woven basket. Autumn field background, dramatic lighting, ultra detailed 8K.', '["carrying the basket at the hip, three-quarter camera, stubble field behind","close portrait from the chest up, autumn light, hedgerow soft behind","wide full-body framing on the lane, harvest sheaves beyond","turning toward the camera, low angle, bare trees behind","mid-stride along the track, side profile camera, long shadows ahead"]'::jsonb),
-- Harvest Chef (Thanksgiving) — 62 words | worst assembled: Natural 329 / Mascot 333 / Cartoon 336
  ('Harvest Chef', 'Thanksgiving', '', 'Cute [TRIGGER_WORD] as a harvest chef, upright in a farmhouse kitchen. Wearing a plain flannel shirt with rolled cuffs, a plain canvas apron over it, plain denim trousers covering both legs to the ankle, and worn leather boots. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one pumpkin pie. Farmhouse kitchen background, warm lighting, ultra detailed 8K.', '["holding the pie toward the camera, front-on framing, steam rising","close portrait from the chest up, warm light, dresser soft behind","wide full-body framing by the table, gourds and corn piled beside","turning from the range, side profile camera, window light behind","setting the pie down, three-quarter camera, kitchen glowing warm"]'::jsonb),
-- Autumn Portrait (Thanksgiving) — 57 words | worst assembled: Natural 313 / Mascot 317 / Cartoon 319
  ('Autumn Portrait', 'Thanksgiving', '', 'Cute [TRIGGER_WORD] in an autumn portrait, upright among fallen leaves. Wearing a plain cable-knit sweater, a plain knit scarf around the neck, plain corduroy trousers covering both legs to the ankle, and worn boots. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one small pumpkin. Woodland background, dramatic lighting, ultra detailed 8K.', '["holding the pumpkin at the chest, three-quarter camera, leaves drifting past","close portrait from the chest up, golden light, branches soft behind","wide full-body framing among the leaves, woodland receding beyond","turning toward the camera, low angle, canopy glowing above","mid-stride along the path, side profile camera, long shadows ahead"]'::jsonb),
-- Uncle Sam (4th of July) — 70 words | worst assembled: Natural 321 / Mascot 325 / Cartoon 327
  ('Uncle Sam', '4th of July', '', 'Cute [TRIGGER_WORD] as Uncle Sam, upright on a parade street. Wearing a plain blue tailcoat, a plain white shirt with a ribbon tie, red and white striped trousers covering both legs to the ankle, and polished shoes. A tall star-spangled top hat sits back from the eyes with a plain band around the crown. Fur shows only on the head, forepaws and tail. Parade background, dramatic lighting, ultra detailed 8K.', '["arm raised in greeting, low heroic camera, bunting strung behind","close portrait from the chest up, bright daylight, flags soft behind","wide full-body framing on the street, parade crowd beyond","turning toward the camera, three-quarter framing, bunting overhead","mid-stride down the parade route, side profile camera, flags lining"]'::jsonb),
-- Stars and Stripes (4th of July) — 64 words | worst assembled: Natural 319 / Mascot 323 / Cartoon 326
  ('Stars and Stripes', '4th of July', '', 'Cute [TRIGGER_WORD] in a stars and stripes celebration, upright at dusk. Wearing a plain flag-patterned shirt, a plain cloth sash across the chest, plain blue trousers covering both legs to the ankle, and canvas shoes. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one lit sparkler. Fireworks fill the sky behind. Night sky background, dramatic lighting, ultra detailed 8K.', '["raising the sparkler high, low heroic camera, fireworks bursting above","close portrait from the chest up, warm sparks, night sky behind","wide full-body framing on the lawn, fireworks scattered above","turning toward the camera, three-quarter framing, sparks trailing","mid-stride across the grass, side profile camera, sky glowing behind"]'::jsonb),
-- Backyard Barbecue (4th of July) — 66 words | worst assembled: Natural 317 / Mascot 321 / Cartoon 323
  ('Backyard Barbecue', '4th of July', '', 'Cute [TRIGGER_WORD] at a backyard barbecue, upright at the grill. Wearing a plain canvas apron over a plain short-sleeved shirt, plain shorts to the knee, and canvas shoes. A plain chef hat sits back from the eyes. Fur shows on the head, forepaws, lower legs and tail. Both forepaws hold exactly one pair of tongs. Backyard background with bunting strung above, warm lighting, ultra detailed 8K.', '["turning food on the grill, three-quarter camera, smoke drifting up","close portrait from the chest up, sunlit, bunting soft behind","wide full-body framing by the grill, garden table beyond","raising the tongs in greeting, low angle, bunting strung above","mid-stride across the lawn, side profile camera, fence line behind"]'::jsonb),
-- Founding Father (Historical) — 68 words | worst assembled: Natural 326 / Mascot 330 / Cartoon 332
  ('Founding Father', 'Historical', '', 'Cute [TRIGGER_WORD] as a founding father, upright in a panelled hall. Wearing a plain deep blue colonial coat, a plain embroidered waistcoat, a plain cloth sash across the chest, plain breeches with tall stockings covering both legs, and buckled shoes. A powdered wig sits above the face, fully visible. The tricorn hat is off, resting on the desk beside them. Panelled hall background, dramatic lighting, ultra detailed 8K.', '["gesturing toward the desk, three-quarter camera, candlelight warm behind","close portrait from the chest up, window light, panelling soft behind","wide full-body framing in the hall, tall windows beyond","turning toward the camera, low angle, chandelier glowing above","mid-stride across the floorboards, side profile camera, long shadows"]'::jsonb),
-- Roman Emperor (Historical) — 60 words | worst assembled: Natural 314 / Mascot 318 / Cartoon 320
  ('Roman Emperor', 'Historical', '', 'Cute [TRIGGER_WORD] as a Roman emperor, upright on marble steps. Wearing a plain white linen toga draped over one shoulder, a plain crimson sash across the chest, a plain leather cincture, and leather sandals. A laurel wreath rests above the face, fully visible. Fur shows only on the head, forepaws and tail. Marble colonnade background, dramatic lighting, ultra detailed 8K.', '["raising one arm in address, low heroic camera, colonnade receding behind","close portrait from the chest up, warm marble light, columns soft behind","wide full-body framing on the steps, forum stretching beyond","turning toward the camera, three-quarter framing, drapes hanging above","mid-stride along the colonnade, side profile camera, long shadows"]'::jsonb),
-- Egyptian Pharaoh (Historical) — 67 words | worst assembled: Natural 323 / Mascot 327 / Cartoon 329
  ('Egyptian Pharaoh', 'Historical', '', 'Cute [TRIGGER_WORD] as an Egyptian pharaoh, upright in a temple hall. Wearing a plain white linen kilt, a broad plain gold collar plate across the chest, a plain woven belt, and leather sandals. A striped nemes headdress frames the face, fully visible. Fur shows on the head, forepaws, lower legs and tail. Both forepaws grip exactly one golden crook. Temple hall background, dramatic lighting, ultra detailed 8K.', '["raising the crook, low heroic camera, carved columns behind","close portrait from the chest up, torchlight warm, carvings soft behind","wide full-body framing in the hall, columns receding beyond","turning toward the camera, three-quarter framing, sunlight shafting down","mid-stride across the stone floor, side profile camera, long shadows"]'::jsonb),
-- Napoleonic General (Historical) — 69 words | worst assembled: Natural 326 / Mascot 330 / Cartoon 333
  ('Napoleonic General', 'Historical', '', 'Cute [TRIGGER_WORD] as a Napoleonic general, upright on a field rise. Wearing a plain dark blue tailcoat with plain gold epaulettes, a plain white sash across the chest, plain white breeches with tall boots covering both legs, and white gloves. The bicorne hat is off, resting on a drum beside them, face fully visible. Both forepaws grip exactly one sheathed sword. Open field background, dramatic lighting, ultra detailed 8K.', '["raising the sword in signal, low heroic camera, field stretching behind","close portrait from the chest up, overcast light, field soft behind","wide full-body framing on the rise, distant lines beyond","turning toward the camera, three-quarter framing, sky heavy above","mid-stride across the grass, side profile camera, long shadows ahead"]'::jsonb),
-- Medieval Queen (Historical) — 69 words | worst assembled: Natural 324 / Mascot 328 / Cartoon 331
  ('Medieval Queen', 'Historical', '', 'Cute [TRIGGER_WORD] as a medieval queen, upright in a stone hall. Wearing a plain deep green velvet gown to the floor, a plain embroidered chest sash, a plain fleece-lined cloak at the shoulders, and soft slippers. A small plain crown sits back from the eyes. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one closed book. Stone hall background, dramatic lighting, ultra detailed 8K.', '["holding the book at the waist, three-quarter camera, tapestries behind","close portrait from the chest up, candlelight warm, stone soft behind","wide full-body framing in the hall, arched windows beyond","turning toward the camera, low angle, torchlight flickering behind","mid-stride across the flagstones, side profile camera, long shadows"]'::jsonb),
-- Viking Chieftain (Historical) — 78 words | worst assembled: Natural 339 / Mascot 343 / Cartoon 345
  ('Viking Chieftain', 'Historical', '', 'Cute [TRIGGER_WORD] as a Viking chieftain, upright on a rocky shore. Wearing a plain wool tunic, a plain cloth sash across the chest, a plain fleece-lined cloak at the shoulders, plain wrapped trousers covering both legs to the ankle, and leather boots. Fur shows only on the head, forepaws and tail. A plain round helmet rests on a rock beside them, face fully visible. Both forepaws grip exactly one axe. Rocky shore background, dramatic lighting, ultra detailed 8K.', '["raising the axe overhead, low heroic camera, longship beyond","close portrait from the chest up, cold light, sea soft behind","wide full-body framing on the shore, waves breaking beyond","turning toward the camera, three-quarter framing, cliffs rising behind","mid-stride across the shingle, side profile camera, spray drifting"]'::jsonb),
-- Samurai (Historical) — 75 words | worst assembled: Natural 338 / Mascot 342 / Cartoon 344
  ('Samurai', 'Historical', '', 'Cute [TRIGGER_WORD] as a samurai, upright in a temple garden. Wearing plain layered lacquered armour with a plain chest plate, plain armoured sleeves on both forearms, plain wrapped trousers covering both legs to the ankle, and corded sandals. Fur shows only on the head, forepaws and tail. The helmet is off, resting on a stone beside them, face fully visible. Both forepaws grip exactly one sheathed katana. Temple garden background, dramatic lighting, ultra detailed 8K.', '["drawing the katana slowly, side profile camera, blossom drifting past","close portrait from the chest up, soft light, garden soft behind","wide full-body framing on the gravel, temple roof beyond","turning toward the camera, three-quarter framing, maples glowing behind","mid-stride along the path, low angle, stone markers lining the way"]'::jsonb),
-- Jazz Age Dapper (Historical) — 75 words | worst assembled: Natural 327 / Mascot 331 / Cartoon 333
  ('Jazz Age Dapper', 'Historical', '', 'Cute [TRIGGER_WORD] as a 1920s jazz age dapper, upright in a club doorway. Wearing a plain pinstripe suit jacket, a plain white shirt with a dark tie, a plain pocket square, plain pinstripe trousers covering both legs to the ankle, and polished shoes. A felt fedora sits back from the eyes with a plain band around the crown. Fur shows only on the head, forepaws and tail. Jazz club background, warm lighting, ultra detailed 8K.', '["adjusting the cuff, three-quarter camera, club lights warm behind","close portrait from the chest up, smoky light, brass glinting behind","wide full-body framing in the doorway, marquee glow beyond","turning toward the camera, low angle, neon spilling across","mid-stride along the sidewalk, side profile camera, streetlights receding"]'::jsonb),
-- Caped Hero (Heroes) — 64 words | worst assembled: Natural 313 / Mascot 317 / Cartoon 319
  ('Caped Hero', 'Heroes', '', 'Cute [TRIGGER_WORD] as a caped hero, upright and powerful. Wearing an original plain deep blue fitted suit with a plain chest panel, a plain crimson cape at the shoulders, a plain wide belt, and tall boots covering both legs to the knee. Fur shows only on the head, forepaws and tail. The face is fully uncovered. City rooftop background, dramatic lighting, ultra detailed 8K.', '["wind lifting behind, low heroic camera, skyline glowing beyond","close portrait from the chest up, dawn light, rooftops soft behind","wide full-body framing on the ledge, city stretching beyond","turning toward the camera, three-quarter framing, clouds racing above","mid-stride across the rooftop, side profile camera, sun low behind"]'::jsonb),
-- Armoured Tech Hero (Heroes) — 65 words | worst assembled: Natural 319 / Mascot 323 / Cartoon 325
  ('Armoured Tech Hero', 'Heroes', '', 'Cute [TRIGGER_WORD] as an armoured tech hero, upright in a hangar. Wearing sleek original plain armour plating over the torso and both legs, a plain chest plate at the centre, plain armoured gloves over both forepaws, and heavy boots. Fur shows only on the head and tail. The helmet is off, held under one forepaw, face fully visible. Hangar background, dramatic lighting, ultra detailed 8K.', '["powering up with light spilling outward, low heroic camera, hangar deep behind","close portrait from the chest up, cool light, gantries soft behind","wide full-body framing on the platform, hangar doors opening beyond","turning toward the camera, three-quarter framing, sparks drifting past","mid-stride down the walkway, side profile camera, lights receding"]'::jsonb),
-- Masked Vigilante (Heroes) — 67 words | worst assembled: Natural 321 / Mascot 325 / Cartoon 328
  ('Masked Vigilante', 'Heroes', '', 'Cute [TRIGGER_WORD] as a masked vigilante, upright on a rooftop. Wearing an original plain charcoal fitted suit with a plain chest panel, a plain utility belt, plain armoured forearm guards, and tall boots covering both legs to the knee. Fur shows only on the head, forepaws and tail. The mask is pushed up on the forehead, face fully visible. Night rooftop background, dramatic lighting, ultra detailed 8K.', '["scanning the street below, low three-quarter camera, neon glowing behind","close portrait from the chest up, rain-slick light, city soft behind","wide full-body framing on the ledge, skyline stretching beyond","turning toward the camera, three-quarter framing, rain drifting past","mid-stride across the roof, side profile camera, searchlight sweeping"]'::jsonb),
-- Flying Hero (Heroes) — 68 words | worst assembled: Natural 320 / Mascot 324 / Cartoon 326
  ('Flying Hero', 'Heroes', '', 'Cute [TRIGGER_WORD] as a flying hero, upright on an airfield. Wearing a plain brown leather flight jacket with a plain chest panel, a plain long scarf at the neck, plain canvas trousers covering both legs to the ankle, and laced boots. Fur shows only on the head, forepaws and tail. The goggles are pushed up on the forehead, face fully visible. Airfield background, dramatic lighting, ultra detailed 8K.', '["wind streaming past, low heroic camera, propeller blurred behind","close portrait from the chest up, golden hour, sky soft behind","wide full-body framing on the grass, biplane parked beyond","turning toward the camera, three-quarter framing, clouds piling above","mid-stride across the airfield, side profile camera, hangars receding"]'::jsonb),
-- Super Strength Hero (Heroes) — 61 words | worst assembled: Natural 313 / Mascot 317 / Cartoon 320
  ('Super Strength Hero', 'Heroes', '', 'Cute [TRIGGER_WORD] as a super strength hero, upright in an arena. Wearing a plain sleeveless singlet, a wide plain belt with a plain square buckle, plain fitted shorts to mid-thigh, and plain wrist wraps on both forearms. Fur shows on the head, forepaws, lower legs and tail. Both forepaws grip exactly one thick barbell. Arena background, dramatic lighting, ultra detailed 8K.', '["lifting the barbell overhead, low heroic camera, arena lights flaring","close portrait from the chest up, hard light, arena soft behind","wide full-body framing on the platform, seating rising beyond","turning toward the camera, three-quarter framing, chalk dust drifting","arms raised in celebration, low angle, spotlights burning above"]'::jsonb)
;

-- Sanity check: expect 47 rows, every one carrying [TRIGGER_WORD] and 5 variants.
select id, name, category, length(base_prompt) as chars,
       position('[TRIGGER_WORD]' in base_prompt) > 0 as has_trigger,
       jsonb_array_length(variants) as variant_count,
       (image = '') as needs_thumbnail
from public.styles
where name in ('Rowing', 'Archery', 'Curling', 'Darts', 'Billiards', 'Bowling', 'Sailboat Racer', 'Race Car Driver', 'Motocross Racer', 'Softball', 'Swimmer', 'Rugby', 'Lacrosse', 'Field Hockey', 'Track and Field', 'Tennis', 'Aussie Rules Football', 'Santa Claus', 'Mrs. Claus', 'Elf', 'Gingerbread Man', 'Snowman', 'Christmas Angel', 'Christmas Fairy', 'Wise Man', 'Nativity Visitor', 'Cosy Christmas', 'Reindeer Helper', 'Pilgrim', 'Harvest Chef', 'Autumn Portrait', 'Uncle Sam', 'Stars and Stripes', 'Backyard Barbecue', 'Founding Father', 'Roman Emperor', 'Egyptian Pharaoh', 'Napoleonic General', 'Medieval Queen', 'Viking Chieftain', 'Samurai', 'Jazz Age Dapper', 'Caped Hero', 'Armoured Tech Hero', 'Masked Vigilante', 'Flying Hero', 'Super Strength Hero')
order by category, name;

commit;
