-- insert-fantasy-intergalactic-construction-themes-2026-09-19.sql
-- 34 new themes: 4 construction trades (Professions), 15 Fantasy, 15 Intergalactic.
-- Run extend-category-enum-2.sql FIRST -- category is cast to the enum type below.
-- Same shape as insert-styles-themes.sql: re-runnable via `where not exists`,
-- image left as '' pending real thumbnails (see thumbnail-checklist.md workflow).
-- No in-prompt naming text on purpose -- pet-name placement is code-driven
-- (NAME_PLACEMENTS in src/utils/fal_utils.ts); see the matching fal_utils.ts
-- diff for the 34 NAME_PLACEMENTS entries these themes need before they can
-- generate correctly.

insert into public.styles (name, category, image, base_prompt, variants)
select v.name, v.category::"GENERATION_CATEGORY", v.image, v.base_prompt, v.variants
from (
  values

-- ===================== CONSTRUCTION TRADES (Professions) =====================

    ('Construction Worker', 'Professions', '', 'Cute [TRIGGER_WORD] as a construction worker, upright on an active job site. Wearing a plain hi-vis safety vest over a plain grey t-shirt, a tool belt at the waist, plain denim trousers covering both legs to the ankle, and sturdy work boots. Fur shows only on the head, forepaws and tail. The hard hat is plain and worn low, face fully visible. Both forepaws grip exactly one shovel. Active construction site background, steel framing behind, dramatic lighting, ultra detailed 8K.', '["gripping the shovel toward the camera, front-on framing, dust in the air","close portrait from the chest up, hard hat catching the light, site soft behind","wide full-body framing by the framing, cranes rising beyond","turning from the site, three-quarter camera, steel beams glowing behind"]'::jsonb),

    ('Mason', 'Professions', '', 'Cute [TRIGGER_WORD] as a mason, upright at the wall. Wearing a plain canvas work apron over a plain flannel shirt, a tool belt hung with pouches, plain denim trousers covering both legs to the ankle, and sturdy work boots. Fur shows only on the head, forepaws and tail. The hard hat is plain and worn low, face fully visible. Both forepaws grip exactly one trowel. Brick wall under construction background, dramatic lighting, ultra detailed 8K.', '["holding the trowel toward the camera, front-on framing, mortar fresh on the blade","close portrait from the chest up, apron soft behind, warm light","wide full-body framing at the wall, brick courses rising beside","three-quarter camera angle, mortar board glowing behind"]'::jsonb),

    ('Roofer', 'Professions', '', 'Cute [TRIGGER_WORD] as a roofer, upright on the rooftop. Wearing a plain long-sleeved work shirt, a tool belt at the waist, plain canvas trousers covering both legs to the ankle, and rubber-soled work boots. Fur shows only on the head, forepaws and tail. The hard hat is plain and worn low, face fully visible. Both forepaws grip exactly one bundle of shingles. Open rooftop background, blue sky behind, dramatic lighting, ultra detailed 8K.', '["holding the shingle bundle toward the camera, front-on framing, sky bright behind","close portrait from the chest up, sun catching the hard hat, rooftop soft behind","wide full-body framing on the rooftop, chimney stacks beside","three-quarter camera angle, open sky glowing behind"]'::jsonb),

    ('Framer', 'Professions', '', 'Cute [TRIGGER_WORD] as a framer, upright at a wood-framed house. Wearing a plain flannel shirt, a tool belt heavy with a hammer loop, plain denim trousers covering both legs to the ankle, and sturdy work boots. Fur shows only on the head, forepaws and tail. The hard hat is plain and worn low, face fully visible. Both forepaws grip exactly one framing hammer. Wood-framed house background, exposed studs behind, dramatic lighting, ultra detailed 8K.', '["gripping the framing hammer toward the camera, front-on framing, sawdust in the air","close portrait from the chest up, warm light, studs soft behind","wide full-body framing at the house, exposed beams rising beside","three-quarter camera angle, framed walls glowing behind"]'::jsonb),

-- ===================== FANTASY (15) =====================

    ('Wizard', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a wizard, upright at the spell circle. Wearing a plain deep-blue robe with wide sleeves, a plain rope cincture at the waist, and soft leather boots beneath the hem. Fur shows only on the head, forepaws and tail. The pointed hat sits back from the brow, face fully visible. Both forepaws grip exactly one gnarled wooden staff. Candlelit study background, mystical glow, ultra detailed 8K.', '["holding the staff toward the camera, front-on framing, sparks at the tip","close portrait from the chest up, candle glow soft behind","wide full-body framing at the spell circle, runes glowing beside","three-quarter camera angle, bookshelves glowing behind"]'::jsonb),

    ('Knight in Shining Armor', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a knight, upright before the castle gate. Wearing a plain polished steel breastplate, plain chainmail sleeves, and plain steel greaves covering both legs to the ankle. Fur shows only on the head, forepaws and tail. The helm is off, tucked under one forepaw, face fully visible. Both forepaws grip exactly one longsword, point resting on the ground. Castle courtyard background, dramatic lighting, ultra detailed 8K.', '["gripping the sword hilt toward the camera, front-on framing, armor gleaming","close portrait from the chest up, sun catching the breastplate, gate soft behind","wide full-body framing at the gate, banners hanging beside","three-quarter camera angle, castle towers glowing behind"]'::jsonb),

    ('Elf Ranger', 'Fantasy', '', 'Cute [TRIGGER_WORD] as an elf ranger, upright at the forest edge. Wearing a plain forest-green hooded cloak, a plain leather vest, and plain suede trousers covering both legs to the ankle. Fur shows only on the head, forepaws and tail. The hood is down, face fully visible. Both forepaws grip exactly one longbow. Deep forest background, dappled sunlight, ultra detailed 8K.', '["holding the bow toward the camera, front-on framing, arrow nocked","close portrait from the chest up, dappled light soft behind","wide full-body framing at the forest edge, ferns beside","three-quarter camera angle, canopy glowing behind"]'::jsonb),

    ('Pixie', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a pixie, upright on a toadstool. Wearing a plain petal-leaf dress with a fitted bodice, and plain woven leggings covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Two delicate translucent wings rise from the shoulders. Both forepaws grip exactly one glowing wand. Moonlit glade background, soft magical glow, ultra detailed 8K.', '["holding the wand toward the camera, front-on framing, sparkles drifting","close portrait from the chest up, moonlight soft behind","wide full-body framing on the toadstool, fireflies beside","three-quarter camera angle, glade glowing behind"]'::jsonb),

    ('Dragon Rider', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a dragon rider, upright in the saddle. Wearing a plain fitted leather flight jacket, plain riding gloves over both forepaws, and plain leather riding trousers covering both legs to the boot. Fur shows only on the head and tail. A dragon''s scaled shoulder and folded wing rise behind. Both forepaws grip exactly one set of leather reins. Cloudtop sky background, dramatic lighting, ultra detailed 8K.', '["gripping the reins toward the camera, front-on framing, wind in the jacket","close portrait from the chest up, clouds soft behind","wide full-body framing in the saddle, dragon scales beside","three-quarter camera angle, sky glowing behind"]'::jsonb),

    ('Royal Sorceress', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a royal sorceress, upright in the throne hall. Wearing a plain flowing violet gown with a fitted bodice, and plain velvet gloves over both forepaws. Fur shows only on the head, forepaws and tail. A jeweled circlet rests on the brow, face fully visible. Both forepaws cradle exactly one glowing crystal orb. Grand hall background, dramatic lighting, ultra detailed 8K.', '["cradling the orb toward the camera, front-on framing, light pulsing within","close portrait from the chest up, hall soft behind","wide full-body framing on the dais, columns beside","three-quarter camera angle, hall glowing behind"]'::jsonb),

    ('Troll', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a troll, upright beneath the bridge. Wearing a plain rough burlap vest, and a plain leather loincloth wrap covering both legs to the knee. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one massive stone club, resting on one shoulder. Mossy stone bridge background, dim atmospheric lighting, ultra detailed 8K.', '["gripping the club toward the camera, front-on framing, moss underfoot","close portrait from the chest up, dim light soft behind","wide full-body framing under the bridge, stones beside","three-quarter camera angle, bridge arch glowing behind"]'::jsonb),

    ('Gnome', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a gnome, upright in the garden. Wearing a plain red tunic with a rope belt, and plain brown trousers covering both legs to the ankle. Fur shows only on the head, forepaws and tail. The pointed cap sits back from the brow, face fully visible. Both forepaws grip exactly one brass lantern. Mushroom garden background, warm glow, ultra detailed 8K.', '["holding the lantern toward the camera, front-on framing, warm light spilling out","close portrait from the chest up, garden soft behind","wide full-body framing among mushrooms, toadstools beside","three-quarter camera angle, garden glowing behind"]'::jsonb),

    ('Dwarf Lord', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a dwarf lord, upright in the great hall. Wearing a plain fur-trimmed leather vest over chainmail, and plain iron-shod boots covering both legs to the knee. Fur shows only on the head, forepaws and tail. A braided beard clasp sits at the chin, face fully visible. Both forepaws grip exactly one battle-axe, head resting on the ground. Stone great hall background, torchlit glow, ultra detailed 8K.', '["gripping the axe toward the camera, front-on framing, torchlight flickering","close portrait from the chest up, hall soft behind","wide full-body framing in the hall, columns beside","three-quarter camera angle, torches glowing behind"]'::jsonb),

    ('Necromancer', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a necromancer, upright in the crypt. Wearing a plain black hooded robe with wide sleeves, and plain dark leather boots beneath the hem covering both legs to the ankle. Fur shows only on the head, forepaws and tail. The hood is down, face fully visible. Both forepaws grip exactly one skull-topped staff. Candlelit crypt background, eerie green glow, ultra detailed 8K.', '["gripping the staff toward the camera, front-on framing, green light pulsing","close portrait from the chest up, crypt soft behind","wide full-body framing in the crypt, candles beside","three-quarter camera angle, crypt glowing behind"]'::jsonb),

    ('Barbarian', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a barbarian, upright on the battlefield. Wearing a plain fur pelt draped over one shoulder, plain leather armor across the chest, and plain wrapped leather leggings covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one massive broadsword, point resting on the ground. Windswept plains background, dramatic lighting, ultra detailed 8K.', '["gripping the broadsword toward the camera, front-on framing, wind in the pelt","close portrait from the chest up, plains soft behind","wide full-body framing on the battlefield, banners beside","three-quarter camera angle, sky glowing behind"]'::jsonb),

    ('Thief', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a thief, upright on the rooftop. Wearing a plain dark hooded cloak, a plain leather chest harness, and plain fitted trousers covering both legs to the ankle. Fur shows only on the head, forepaws and tail. The hood is down, face fully visible. Both forepaws grip exactly one pair of twin daggers, crossed. Moonlit rooftops background, shadowy lighting, ultra detailed 8K.', '["holding the daggers toward the camera, front-on framing, moonlight on the blades","close portrait from the chest up, rooftops soft behind","wide full-body framing on the rooftop, chimneys beside","three-quarter camera angle, skyline glowing behind"]'::jsonb),

    ('Bard', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a bard, upright on the tavern stage. Wearing a plain feathered cap, a plain velvet doublet, and plain fitted trousers covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one lute, strings toward the camera. Cozy tavern background, warm lighting, ultra detailed 8K.', '["holding the lute toward the camera, front-on framing, mid-strum","close portrait from the chest up, tavern soft behind","wide full-body framing on the stage, barrels beside","three-quarter camera angle, hearth glowing behind"]'::jsonb),

    ('Witch', 'Fantasy', '', 'Cute [TRIGGER_WORD] as a witch, upright in the moonlit clearing. Wearing a plain black pointed hat, a plain patched shawl over a plain dark dress, and plain buckled boots covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one broomstick, held upright. Moonlit clearing background, mystical glow, ultra detailed 8K.', '["gripping the broomstick toward the camera, front-on framing, mist curling low","close portrait from the chest up, moonlight soft behind","wide full-body framing in the clearing, cauldron beside","three-quarter camera angle, clearing glowing behind"]'::jsonb),

    ('Alchemist', 'Fantasy', '', 'Cute [TRIGGER_WORD] as an alchemist, upright at the workbench. Wearing a plain stained apron over a plain collared shirt, and plain dark trousers covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Round spectacles sit low on the nose, face fully visible. Both forepaws hold exactly one bubbling potion flask. Cluttered alchemy den background, warm glow, ultra detailed 8K.', '["holding the flask toward the camera, front-on framing, potion bubbling","close portrait from the chest up, den soft behind","wide full-body framing at the bench, bottles beside","three-quarter camera angle, shelves glowing behind"]'::jsonb),

-- ===================== INTERGALACTIC (15) =====================

    ('Space Marine', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as a space marine, upright on patrol. Wearing a plain matte-grey combat suit with segmented plating, plain armored gauntlets over both forepaws, and plain armored boots covering both legs to the knee. Fur shows only on the head and tail. The helmet is off, held under one forepaw, face fully visible. Both forepaws grip exactly one plasma rifle. Starship corridor background, dramatic lighting, ultra detailed 8K.', '["gripping the rifle toward the camera, front-on framing, corridor lights flickering","close portrait from the chest up, corridor soft behind","wide full-body framing in the corridor, panels beside","three-quarter camera angle, lights glowing behind"]'::jsonb),

    ('Starship Captain', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as a starship captain, upright on the bridge. Wearing a plain fitted command uniform jacket, and plain uniform trousers covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one holographic command tablet. Starship bridge background, dramatic lighting, ultra detailed 8K.', '["holding the tablet toward the camera, front-on framing, hologram glowing","close portrait from the chest up, bridge soft behind","wide full-body framing on the bridge, viewscreen beside","three-quarter camera angle, stars glowing behind"]'::jsonb),

    ('Galactic Bounty Hunter', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as a galactic bounty hunter, upright on the landing pad. Wearing a plain weathered flight jacket, a plain utility harness across the chest, and plain armored trousers covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one blaster pistol. Starport landing pad background, dramatic lighting, ultra detailed 8K.', '["gripping the blaster toward the camera, front-on framing, engines glowing behind","close portrait from the chest up, landing pad soft behind","wide full-body framing on the pad, ships beside","three-quarter camera angle, starport glowing behind"]'::jsonb),

    ('Smuggler', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as a smuggler, upright in the cargo bay. Wearing a plain battered leather jacket, and plain fitted trousers covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one cargo satchel. Cluttered cargo bay background, dim lighting, ultra detailed 8K.', '["gripping the satchel toward the camera, front-on framing, crates stacked behind","close portrait from the chest up, cargo bay soft behind","wide full-body framing in the bay, crates beside","three-quarter camera angle, bay glowing behind"]'::jsonb),

    ('Space Pirate', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as a space pirate, upright on the boarding ramp. Wearing a plain patched flight suit, a plain bandolier across the chest, and plain scuffed boots covering both legs to the knee. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one plasma cutlass. Derelict ship background, dramatic lighting, ultra detailed 8K.', '["gripping the cutlass toward the camera, front-on framing, sparks arcing off the blade","close portrait from the chest up, derelict ship soft behind","wide full-body framing on the ramp, wreckage beside","three-quarter camera angle, ship glowing behind"]'::jsonb),

    ('Alien Diplomat', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as an alien diplomat, upright in the council chamber. Wearing a plain flowing formal robe with wide sleeves, and plain soft ceremonial slippers covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one ornate ceremonial staff. Galactic council chamber background, dramatic lighting, ultra detailed 8K.', '["gripping the staff toward the camera, front-on framing, chamber lights glowing","close portrait from the chest up, chamber soft behind","wide full-body framing in the chamber, delegates'' seats beside","three-quarter camera angle, chamber glowing behind"]'::jsonb),

    ('Galactic Royalty', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as galactic royalty, upright on the throne dais. Wearing a plain jeweled formal robe, and plain velvet gloves over both forepaws. Fur shows only on the head, forepaws and tail. A crystal circlet rests on the brow, face fully visible. Both forepaws grip exactly one crystal scepter. Star-throne chamber background, dramatic lighting, ultra detailed 8K.', '["gripping the scepter toward the camera, front-on framing, crystal catching the light","close portrait from the chest up, dais soft behind","wide full-body framing on the dais, columns beside","three-quarter camera angle, stars glowing behind"]'::jsonb),

    ('Void Knight', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as a void knight, upright at the airlock. Wearing a plain dark armored plate suit, plain armored gauntlets over both forepaws, and plain armored boots covering both legs to the knee. Fur shows only on the head and tail. The visor is up, face fully visible. Both forepaws grip exactly one glowing energy sword. Starlit void background, dramatic lighting, ultra detailed 8K.', '["gripping the energy sword toward the camera, front-on framing, blade glowing","close portrait from the chest up, void soft behind","wide full-body framing at the airlock, stars beside","three-quarter camera angle, void glowing behind"]'::jsonb),

    ('Cosmic Sorcerer', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as a cosmic sorcerer, upright among the stars. Wearing a plain starlit robe with wide sleeves, and plain soft boots covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Both forepaws cradle exactly one glowing cosmic orb. Nebula background, mystical glow, ultra detailed 8K.', '["cradling the orb toward the camera, front-on framing, nebula swirling within","close portrait from the chest up, nebula soft behind","wide full-body framing among the stars, nebula beside","three-quarter camera angle, nebula glowing behind"]'::jsonb),

    ('Nebula Explorer', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as a nebula explorer, upright at the viewport. Wearing a plain fitted expedition suit, plain utility gloves over both forepaws, and plain expedition boots covering both legs to the knee. Fur shows only on the head and tail. Both forepaws hold exactly one handheld scanner. Nebula viewport background, dramatic lighting, ultra detailed 8K.', '["holding the scanner toward the camera, front-on framing, readout glowing","close portrait from the chest up, viewport soft behind","wide full-body framing at the viewport, nebula beside","three-quarter camera angle, nebula glowing behind"]'::jsonb),

    ('Asteroid Miner', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as an asteroid miner, upright on the rock face. Wearing a plain heavy-duty work suit, plain reinforced gloves over both forepaws, and plain reinforced boots covering both legs to the knee. Fur shows only on the head and tail. The helmet is off, held under one forepaw, face fully visible. Both forepaws grip exactly one mining drill. Asteroid surface background, dramatic lighting, ultra detailed 8K.', '["gripping the drill toward the camera, front-on framing, dust drifting in zero-g","close portrait from the chest up, asteroid soft behind","wide full-body framing on the rock face, stars beside","three-quarter camera angle, asteroid glowing behind"]'::jsonb),

    ('Cyborg Engineer', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as a cyborg engineer, upright at the console. Wearing a plain fitted mechanic jumpsuit, and a plain tool harness across the chest. Fur shows only on the head, forepaws and tail. Both forepaws grip exactly one multitool. Engine room background, dramatic lighting, ultra detailed 8K.', '["gripping the multitool toward the camera, front-on framing, sparks off the console","close portrait from the chest up, engine room soft behind","wide full-body framing at the console, pipes beside","three-quarter camera angle, engine room glowing behind"]'::jsonb),

    ('Android Companion', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as an android companion, upright in the lab. Wearing a plain sleek plated bodysuit, and plain metallic plating covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one glowing data core. Research lab background, dramatic lighting, ultra detailed 8K.', '["holding the data core toward the camera, front-on framing, core pulsing with light","close portrait from the chest up, lab soft behind","wide full-body framing in the lab, monitors beside","three-quarter camera angle, lab glowing behind"]'::jsonb),

    ('Star Cadet', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as a star cadet, upright at attention. Wearing a plain fitted academy uniform jacket, and plain uniform trousers covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Both forepaws hold exactly one datapad. Academy hall background, dramatic lighting, ultra detailed 8K.', '["holding the datapad toward the camera, front-on framing, screen glowing","close portrait from the chest up, academy hall soft behind","wide full-body framing at attention, banners beside","three-quarter camera angle, hall glowing behind"]'::jsonb),

    ('Zero-G Racer', 'Intergalactic', '', 'Cute [TRIGGER_WORD] as a zero-g racer, upright at the starting gate. Wearing a plain sleek racing suit with piping, and plain racing boots covering both legs to the ankle. Fur shows only on the head, forepaws and tail. Face fully visible. Both forepaws hold exactly one racing helmet, tucked against the hip. Starting gate background, dramatic lighting, ultra detailed 8K.', '["holding the helmet toward the camera, front-on framing, gate lights flashing","close portrait from the chest up, starting gate soft behind","wide full-body framing at the gate, other racers beside","three-quarter camera angle, track lights glowing behind"]'::jsonb)

  ) as v(name, category, image, base_prompt, variants)
where not exists (
  select 1 from public.styles s where s.name = v.name
);
